### PR TITLE
XMKTP Dectorio_0.7.5_ko

### PR DESCRIPTION
**Pull request by GimoXagros**
Updated from Xagros [XMKTP] https://mods.factorio.com/mods/Xagros/XMKTP

If you need any further assistance, please do not hesitate to contact me! :D

### CODE REVIEW

**Comment by GimoXagros** [comment]
Updated from Xagros [XMKTP] https://mods.factorio.com/mods/Xagros/XMKTP

If you need any further assistance, please do not hesitate to contact me! :D

**Comment by jpanther** [comment]
Ah, thank you for these! And thanks for posting them to CrowdIn too! I'll be sure to bundle them into the next update.

**Comment by jpanther** [comment]
So I've reviewed the changes that you have bundled into this PR and in your XMKTP repo and I've noticed that you're using a lot of old string names that have changed in Dectorio v0.7.5 so these strings currently will show up as missing. For example, `dect-gui-sign-title` is now just `sign-title` and `dect-notify-version` is now just `version`.

I've attached the CrowdIn export so you can see the correct string names - see [dectorio.cfg](https://github.com/jpanther/Dectorio/files/1493539/dectorio.cfg.txt)

**Comment by GimoXagros** [comment]
Dectorio will not be included in XMKTP in the future. Please contact me if you have any other mod or Dectorio language files to be updated. I will be happy to help you anytime! :)

**Comment by jpanther** [comment]
Thanks, I'll let you know when there are new strings for translation :)

**Pull request merged**
