### PR TITLE
Adds Signs

### LINKED ISSUE #12: Add signs
Could you please add a sign to your mod?
The sign should be able to display any signal/item that there is in game.

It would be fine for me if the sign would only work if I have Alt enabled.

signs

Intended use help navigating on large rail networks and add markers to blueprint where to insert a certain resource.

Suggested specs:

* Size: 1x1 + 2x2 variants
* No collision box/placeable everywhere
* Additional direction signals/images for the rail naviagtion (sketch).
* Colors: Brown (Wood), White and black (iron/steel)

I don't know whether that matches the other features of your mod, so you could also add it to a separate mod.

### PR DESCRIPTION
**Pull request by jpanther**
Adds new wooden and steel signs with selectable icons

### CODE REVIEW

**Comment by jpanther** [comment]
This PR closes #12

**Comment by jpanther** [comment]
Hey @seeba8, I know it's only just after you submitted your translation but I don't suppose you could translate the additional strings in this update? I think theres only 8 new ones.

**Comment by seeba8** [comment]
Can't write a commit/pull request right now. I can do it tonight (probably) or you can do it if you want it earlier:
```
dect-sign-wood=Holzschild
dect-sign-steel=Stahlschild
dect-signs=Schilder
dect-signs=Schilder, die dir helfen deine Fabrik zu beschriften.
dectorio-signs=Aktiviere Schilder
dectorio-signs=Aktiviert die Möglichkeit, Schilder zu herzustellen
```

**Comment by jpanther** [comment]
It's a bit weird the way it merges the pull requests but it did the right thing! Thanks for the additional translations. :)

**Comment by ST-DDT** [comment]
Nice

**Pull request merged**
