### PR TITLE
Add setting that moves items to a dedicated Dectorio item-group.

### PR DESCRIPTION
**Pull request by Aidiakapi**
Moves most (all except the glowing lamp and signals afaik.) items to a dedicated Dectorio `item-group`, if the setting is enabled.

I was only able to provide localisations for English.

### CODE REVIEW

**Comment by jpanther** [comment]
Thanks for the PR, this feature looks really well implemented. I'll do some testing on it now.

**Comment by jpanther** [comment]
Okay, overall this looks good. The only things I'm a little concerned about at the moment are: 
- The sort order when everything is moved to the separate tab is a bit all over the place. The solution to this might be to have different `order` values set on the items depending on whether the setting to have the separate tab is enabled or not; and
- It splits up the defensive structures away from the vanilla ones and this is a little counter-intuitive. I think either the vanilla wall (that Dectorio modifies anyway) needs to be moved as well, or all the walls need to stay together. It may make more sense to leave them on the military tab and just make the Dectorio tab for things that are purely decorative.

**Comment by Aidiakapi** [comment]
Regarding the first point. There's two ways to solve that, one mimicks the previous implementation (since I tried to limit modifications), and just changes the order depending on the original category it was in.

The second, and "most correct" approach would be to create subgroups for each type of Dectorio item, and sort those.

As for walls, I was conflicted on this, since there are many so many walls in the mod. From my personal experience, decorative walls are more likely to be used around rails, and areas of the factory, than actually as defense. However, I do agree that they should be in the same place.

It could be implemented as a separate option, which might be a bit overkill. I think moving the vanilla wall with the Dectorio ones is probably the right choice.

**Comment by jpanther** [comment]
The re-ordering is an easy fix and I think that more groupings is definitely the way to fix it. They aren't too bad how it is, I think it's just a new opportunity to clean it up a bit now it doesn't need to map directly to the vanilla categories.

The walls one is a tough one for me because I think it boils down to whether you consider them decorative or not. For instance, I play a lot of Deathworld and that's partly how the walls came about because I like the technology progression that allows you to get early game walls up and running quickly. So for me it hasn't really been about decorations at all and I've always tried to make anything I add at least have some sort of function so it can justify its existence. I think whatever the decision it needs to be consistent. For instance if we move all the walls to the new tab, the lights should move too.

The real problem with this is twofold. It can be very confusing for people to find these vanilla items when you move them, and when you start modifying the vanilla parts of the game you open yourself up to conflicts with other mods very quickly. I think what I'm leaning towards is keeping the lights and walls where they are and making the Dectorio tab purely for decorations. I think it would flow nicely having groupings for decoratives, signs, floorings and landscaping. I had a bunch more items planned for these categories too but was reluctant to add them due to a lack of crafting menu space so this is also a good opportunity to expand it a bit.

**Comment by jpanther** [comment]
Pulled this into a separate branch to make some changes. I've got the sorting working in a way that makes a bit more sense now and falls back to vanilla reasonably nicely if the user flicks off the setting. Have a look and see what you think.

**Comment by Aidiakapi** [comment]
Alright, I've reviewed the code, and yeah, our perspectives on walls differ. You mainly play Deathworlds, I mainly play Rail Worlds, and in most maps even with biters completely disabled. The millitary aspects of the game don't interest me much.

Regardless, since you've removed the usage of `key` in the metatable, it might as well not be a metatable, and the code would be simpler. I've submitted a PR with the simplification, it's a minor thing, if you have a specific reason for doing it the way you did it, just deny it :).

**Comment by jpanther** [comment]
So I left it with the metatable in because originally I made a table that mapped the values between what they were being categorised as in Dectorio to what they should be in Vanilla... `map_vanilla = { ["decoratives"] = "logistics", ... }` and then returned `map_vanilla[key]` but then I realised they all mapped to logistics anyway. I figured I'd put the mapping back in if it ever got to the point where they'd end up in different categories and so that's how it came about. You're right that it doesn't serve any purpose as it is.

I compromised and didn't bother remapping the subgroups because I figured it would be annoying to have to constantly keep the mappings up to date as new items were added.

**Pull request merged**
